application: read-the-plaque
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /googlea9436158c9d937ee.html
  static_files: googlea9436158c9d937ee.html
  upload: googlea9436158c9d937ee.html

- url: /.*
  script: View.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
