application: read-the-plaque
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /apple-touch-icon.png
  static_files: static/images/apple-touch-icon.png
  upload: static/images/apple-touch-icon.png

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /googlea9436158c9d937ee.html
  static_files: googlea9436158c9d937ee.html
  upload: googlea9436158c9d937ee.html

- url: /static
  static_dir: static

- url: /images
  static_dir: static/images

- url: /pending
  script: View.app
  login: admin

- url: /approve
  script: View.app
  login: admin

- url: /submit-your-own
  script: View.app

- url: /add
  script: View.app

- url: /.*
  script: View.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
